os: linux
dist: trusty
sudo: required
group: edge
language: c

before_script:
  - avr-gcc --version

script:
  - cd .. # pop up to /home/travis/build/issmirnov
  - git clone --depth 1 https://github.com/qmk/qmk_firmware.git
  - cd qmk_firmware
  - ls
  - mkdir -p layouts/community/ergodox/ismirnov # prepare stage
  - mv ../ergodox-layout/* layouts/community/ergodox/ismirnov # move checked out repo files
  - ls layouts/community/ergodox/ismirnov
  - make ergodox_ez:ismirnov 
  
addons:
  apt:
    packages:
    - gcc 
    - unzip 
    - wget 
    - zip 
    - gcc-avr 
    - binutils-avr 
    - avr-libc 
    - dfu-programmer 
    - dfu-util 
    - gcc-arm-none-eabi 
    - binutils-arm-none-eabi 
    - libnewlib-arm-none-eabi
